#ifndef PLATFORM_PLDM_TESTING_H_
#define PLATFORM_PLDM_TESTING_H_


#define PLDM_TESTING_FIRMWARE_DEVICE_PORT           49156
#define PLDM_TESTING_UPDATE_AGENT_PORT              49155

#define PLDM_TESTING_MS_TIMEOUT                     10000

#endif /* PLATFORM_PLDM_TESTING_H_ */